//! Linear adapter — typed GraphQL bindings and (later) the
//! [`crate::IssueTracker`] implementation.
//!
//! This iteration ships only the typed query bindings generated by
//! `graphql_client` from the `.graphql` files in
//! `crates/symphony-tracker/graphql/linear/`. The HTTP adapter that drives
//! these queries against `https://api.linear.app/graphql` lands in the
//! next checklist item.
//!
//! ## Why isolate the query bindings in a submodule
//!
//! SPEC §11.2 warns that "Linear GraphQL schema details can drift" and
//! asks implementations to "keep query construction isolated". Putting the
//! generated `Query`/`Variables`/`ResponseData` types behind
//! `linear::queries` means the rest of the adapter (and certainly the
//! orchestrator) never imports a graphql_client-generated symbol — only
//! the typed handles `CandidateIssues`, `IssuesByStates`, and
//! `IssueStatesByIds`.
//!
//! ## Naming
//!
//! Each operation in `queries.graphql` becomes a unit struct here named
//! after the operation (`CandidateIssues`, etc). The `graphql_client`
//! derive macro then generates a sibling module
//! (`candidate_issues::Variables`, `candidate_issues::ResponseData`, …)
//! with the request/response types. Re-exports below give the rest of the
//! adapter ergonomic names without leaking generated module paths.

pub mod queries;

pub use queries::{
    CandidateIssues, CandidateIssuesVariables, IssueStatesByIds, IssueStatesByIdsVariables,
    IssuesByStates, IssuesByStatesVariables,
};

pub mod adapter;
pub use adapter::{LinearConfig, LinearTracker};
